/*
 * ESSE3 Questionari API
 * API REST di ESSE3 per l'accesso ai questionari
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.epic_guys.esse4.models.questionari;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

/**
 * Answer
 */
public class Answer {
  @SerializedName("domandaId")
  private Integer domandaId = null;

  @SerializedName("rispostaId")
  private Integer rispostaId = null;

  @SerializedName("corpoRisposta")
  private String corpoRisposta = "";

  public Answer domandaId(Integer domandaId) {
    this.domandaId = domandaId;
    return this;
  }

   /**
   * Get domandaId
   * @return domandaId
  **/
  public Integer getDomandaId() {
    return domandaId;
  }

  public void setDomandaId(Integer domandaId) {
    this.domandaId = domandaId;
  }

  public Answer rispostaId(Integer rispostaId) {
    this.rispostaId = rispostaId;
    return this;
  }

   /**
   * Get rispostaId
   * @return rispostaId
  **/
  public Integer getRispostaId() {
    return rispostaId;
  }

  public void setRispostaId(Integer rispostaId) {
    this.rispostaId = rispostaId;
  }

  public Answer corpoRisposta(String corpoRisposta) {
    this.corpoRisposta = corpoRisposta;
    return this;
  }

   /**
   * Get corpoRisposta
   * @return corpoRisposta
  **/
  public String getCorpoRisposta() {
    return corpoRisposta;
  }

  public void setCorpoRisposta(String corpoRisposta) {
    this.corpoRisposta = corpoRisposta;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Answer answer = (Answer) o;
    return Objects.equals(this.domandaId, answer.domandaId) &&
        Objects.equals(this.rispostaId, answer.rispostaId);// &&
        // Objects.equals(this.corpoRisposta, answer.corpoRisposta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domandaId, rispostaId, corpoRisposta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Answer {\n");
    
    sb.append("    domandaId: ").append(toIndentedString(domandaId)).append("\n");
    sb.append("    rispostaId: ").append(toIndentedString(rispostaId)).append("\n");
    sb.append("    corpoRisposta: ").append(toIndentedString(corpoRisposta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

