/*
 * ESSE3 Questionari API
 * API REST di ESSE3 per l'accesso ai questionari
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.epic_guys.esse4.models.questionari;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

/**
 * DominiRisposte
 */
public class DominiRisposte {
  @SerializedName("quesitoId")
  private Integer quesitoId = null;

  @SerializedName("operandoDomId")
  private Integer operandoDomId = null;

  @SerializedName("numMaxValori")
  private Integer numMaxValori = null;

  @SerializedName("questCompId")
  private Integer questCompId = null;

  @SerializedName("desValDom")
  private String desValDom = null;

  public DominiRisposte quesitoId(Integer quesitoId) {
    this.quesitoId = quesitoId;
    return this;
  }

   /**
   * Get quesitoId
   * @return quesitoId
  **/
  
  public Integer getQuesitoId() {
    return quesitoId;
  }

  public void setQuesitoId(Integer quesitoId) {
    this.quesitoId = quesitoId;
  }

  public DominiRisposte operandoDomId(Integer operandoDomId) {
    this.operandoDomId = operandoDomId;
    return this;
  }

   /**
   * Get operandoDomId
   * @return operandoDomId
  **/
  
  public Integer getOperandoDomId() {
    return operandoDomId;
  }

  public void setOperandoDomId(Integer operandoDomId) {
    this.operandoDomId = operandoDomId;
  }

  public DominiRisposte numMaxValori(Integer numMaxValori) {
    this.numMaxValori = numMaxValori;
    return this;
  }

   /**
   * Get numMaxValori
   * @return numMaxValori
  **/
  
  public Integer getNumMaxValori() {
    return numMaxValori;
  }

  public void setNumMaxValori(Integer numMaxValori) {
    this.numMaxValori = numMaxValori;
  }

  public DominiRisposte questCompId(Integer questCompId) {
    this.questCompId = questCompId;
    return this;
  }

   /**
   * Get questCompId
   * @return questCompId
  **/
  
  public Integer getQuestCompId() {
    return questCompId;
  }

  public void setQuestCompId(Integer questCompId) {
    this.questCompId = questCompId;
  }

  public DominiRisposte desValDom(String desValDom) {
    this.desValDom = desValDom;
    return this;
  }

   /**
   * Get desValDom
   * @return desValDom
  **/
  
  public String getDesValDom() {
    return desValDom;
  }

  public void setDesValDom(String desValDom) {
    this.desValDom = desValDom;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DominiRisposte dominiRisposte = (DominiRisposte) o;
    return Objects.equals(this.quesitoId, dominiRisposte.quesitoId) &&
        Objects.equals(this.operandoDomId, dominiRisposte.operandoDomId) &&
        Objects.equals(this.numMaxValori, dominiRisposte.numMaxValori) &&
        Objects.equals(this.questCompId, dominiRisposte.questCompId) &&
        Objects.equals(this.desValDom, dominiRisposte.desValDom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quesitoId, operandoDomId, numMaxValori, questCompId, desValDom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DominiRisposte {\n");
    
    sb.append("    quesitoId: ").append(toIndentedString(quesitoId)).append("\n");
    sb.append("    operandoDomId: ").append(toIndentedString(operandoDomId)).append("\n");
    sb.append("    numMaxValori: ").append(toIndentedString(numMaxValori)).append("\n");
    sb.append("    questCompId: ").append(toIndentedString(questCompId)).append("\n");
    sb.append("    desValDom: ").append(toIndentedString(desValDom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

