/*
 * ESSE3 Questionari API
 * API REST di ESSE3 per l'accesso ai questionari
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.epic_guys.esse4.models.questionari;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/**
 * PaginaQuestionario
 */
public class PaginaQuestionario {
  @SerializedName("paginaId")
  private Integer paginaId = null;

  @SerializedName("elemCod")
  private String elemCod = null;

  @SerializedName("elementiDes")
  private String elementiDes = null;

  @SerializedName("elementiNota")
  private String elementiNota = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("questCompId")
  private Integer questCompId = null;

  @SerializedName("userCompId")
  private Integer userCompId = null;

  @SerializedName("questionarioCod")
  private String questionarioCod = null;

  @SerializedName("pPaginaPrecId")
  private Integer pPaginaPrecId = null;

  @SerializedName("pPaginaSuccId")
  private Integer pPaginaSuccId = null;

  @SerializedName("pQuestionarioDes")
  private String pQuestionarioDes = null;

  @SerializedName("pQuestionarioNote")
  private String pQuestionarioNote = null;

  @SerializedName("questionarioId")
  private Integer questionarioId = null;

  @SerializedName("des")
  private String des = null;

  @SerializedName("numeroRisposte")
  private Integer numeroRisposte = null;

  @SerializedName("paragrafi")
  private List<Paragrafi> paragrafi = null;

  @SerializedName("tagsWeb")
  private List<TagsWeb> tagsWeb = null;

  public PaginaQuestionario paginaId(Integer paginaId) {
    this.paginaId = paginaId;
    return this;
  }

   /**
   * Get paginaId
   * @return paginaId
  **/
  
  public Integer getPaginaId() {
    return paginaId;
  }

  public void setPaginaId(Integer paginaId) {
    this.paginaId = paginaId;
  }

  public PaginaQuestionario elemCod(String elemCod) {
    this.elemCod = elemCod;
    return this;
  }

   /**
   * Get elemCod
   * @return elemCod
  **/
  
  public String getElemCod() {
    return elemCod;
  }

  public void setElemCod(String elemCod) {
    this.elemCod = elemCod;
  }

  public PaginaQuestionario elementiDes(String elementiDes) {
    this.elementiDes = elementiDes;
    return this;
  }

   /**
   * Get elementiDes
   * @return elementiDes
  **/
  
  public String getElementiDes() {
    return elementiDes;
  }

  public void setElementiDes(String elementiDes) {
    this.elementiDes = elementiDes;
  }

  public PaginaQuestionario elementiNota(String elementiNota) {
    this.elementiNota = elementiNota;
    return this;
  }

   /**
   * Get elementiNota
   * @return elementiNota
  **/
  
  public String getElementiNota() {
    return elementiNota;
  }

  public void setElementiNota(String elementiNota) {
    this.elementiNota = elementiNota;
  }

  public PaginaQuestionario note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public PaginaQuestionario questCompId(Integer questCompId) {
    this.questCompId = questCompId;
    return this;
  }

   /**
   * Get questCompId
   * @return questCompId
  **/
  
  public Integer getQuestCompId() {
    return questCompId;
  }

  public void setQuestCompId(Integer questCompId) {
    this.questCompId = questCompId;
  }

  public PaginaQuestionario userCompId(Integer userCompId) {
    this.userCompId = userCompId;
    return this;
  }

   /**
   * Get userCompId
   * @return userCompId
  **/
  
  public Integer getUserCompId() {
    return userCompId;
  }

  public void setUserCompId(Integer userCompId) {
    this.userCompId = userCompId;
  }

  public PaginaQuestionario questionarioCod(String questionarioCod) {
    this.questionarioCod = questionarioCod;
    return this;
  }

   /**
   * Get questionarioCod
   * @return questionarioCod
  **/
  
  public String getQuestionarioCod() {
    return questionarioCod;
  }

  public void setQuestionarioCod(String questionarioCod) {
    this.questionarioCod = questionarioCod;
  }

  public PaginaQuestionario pPaginaPrecId(Integer pPaginaPrecId) {
    this.pPaginaPrecId = pPaginaPrecId;
    return this;
  }

   /**
   * Pagina id della pagina precedente, se è null significa che si è all&#39;inizio della compilazione (Questi campi sono valorizzati solo con lo spostamento tra le pagine)
   * @return pPaginaPrecId
  **/
  
  public Integer getPPaginaPrecId() {
    return pPaginaPrecId;
  }

  public void setPPaginaPrecId(Integer pPaginaPrecId) {
    this.pPaginaPrecId = pPaginaPrecId;
  }

  public PaginaQuestionario pPaginaSuccId(Integer pPaginaSuccId) {
    this.pPaginaSuccId = pPaginaSuccId;
    return this;
  }

   /**
   * Pagina id della pagina successiva, se è null significa che si è alla fine della compilazione ed è necessario chiamare il riepilogo (Questi campi sono valorizzati solo con lo spostamento tra le pagine)
   * @return pPaginaSuccId
  **/
  
  public Integer getPPaginaSuccId() {
    return pPaginaSuccId;
  }

  public void setPPaginaSuccId(Integer pPaginaSuccId) {
    this.pPaginaSuccId = pPaginaSuccId;
  }

  public PaginaQuestionario pQuestionarioDes(String pQuestionarioDes) {
    this.pQuestionarioDes = pQuestionarioDes;
    return this;
  }

   /**
   * Get pQuestionarioDes
   * @return pQuestionarioDes
  **/
  
  public String getPQuestionarioDes() {
    return pQuestionarioDes;
  }

  public void setPQuestionarioDes(String pQuestionarioDes) {
    this.pQuestionarioDes = pQuestionarioDes;
  }

  public PaginaQuestionario pQuestionarioNote(String pQuestionarioNote) {
    this.pQuestionarioNote = pQuestionarioNote;
    return this;
  }

   /**
   * Get pQuestionarioNote
   * @return pQuestionarioNote
  **/
  
  public String getPQuestionarioNote() {
    return pQuestionarioNote;
  }

  public void setPQuestionarioNote(String pQuestionarioNote) {
    this.pQuestionarioNote = pQuestionarioNote;
  }

  public PaginaQuestionario questionarioId(Integer questionarioId) {
    this.questionarioId = questionarioId;
    return this;
  }

   /**
   * Get questionarioId
   * @return questionarioId
  **/
  
  public Integer getQuestionarioId() {
    return questionarioId;
  }

  public void setQuestionarioId(Integer questionarioId) {
    this.questionarioId = questionarioId;
  }

  public PaginaQuestionario des(String des) {
    this.des = des;
    return this;
  }

   /**
   * Get des
   * @return des
  **/
  
  public String getDes() {
    return des;
  }

  public void setDes(String des) {
    this.des = des;
  }

  public PaginaQuestionario numeroRisposte(Integer numeroRisposte) {
    this.numeroRisposte = numeroRisposte;
    return this;
  }

   /**
   * Get numeroRisposte
   * @return numeroRisposte
  **/
  
  public Integer getNumeroRisposte() {
    return numeroRisposte;
  }

  public void setNumeroRisposte(Integer numeroRisposte) {
    this.numeroRisposte = numeroRisposte;
  }

  public PaginaQuestionario paragrafi(List<Paragrafi> paragrafi) {
    this.paragrafi = paragrafi;
    return this;
  }

  public PaginaQuestionario addParagrafiItem(Paragrafi paragrafiItem) {
    if (this.paragrafi == null) {
      this.paragrafi = new ArrayList<Paragrafi>();
    }
    this.paragrafi.add(paragrafiItem);
    return this;
  }

   /**
   * Get paragrafi
   * @return paragrafi
  **/
  
  public List<Paragrafi> getParagrafi() {
    return paragrafi;
  }

  public void setParagrafi(List<Paragrafi> paragrafi) {
    this.paragrafi = paragrafi;
  }

  public PaginaQuestionario tagsWeb(List<TagsWeb> tagsWeb) {
    this.tagsWeb = tagsWeb;
    return this;
  }

  public PaginaQuestionario addTagsWebItem(TagsWeb tagsWebItem) {
    if (this.tagsWeb == null) {
      this.tagsWeb = new ArrayList<TagsWeb>();
    }
    this.tagsWeb.add(tagsWebItem);
    return this;
  }

   /**
   * Get tagsWeb
   * @return tagsWeb
  **/
  
  public List<TagsWeb> getTagsWeb() {
    return tagsWeb;
  }

  public void setTagsWeb(List<TagsWeb> tagsWeb) {
    this.tagsWeb = tagsWeb;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginaQuestionario paginaQuestionario = (PaginaQuestionario) o;
    return Objects.equals(this.paginaId, paginaQuestionario.paginaId) &&
        Objects.equals(this.elemCod, paginaQuestionario.elemCod) &&
        Objects.equals(this.elementiDes, paginaQuestionario.elementiDes) &&
        Objects.equals(this.elementiNota, paginaQuestionario.elementiNota) &&
        Objects.equals(this.note, paginaQuestionario.note) &&
        Objects.equals(this.questCompId, paginaQuestionario.questCompId) &&
        Objects.equals(this.userCompId, paginaQuestionario.userCompId) &&
        Objects.equals(this.questionarioCod, paginaQuestionario.questionarioCod) &&
        Objects.equals(this.pPaginaPrecId, paginaQuestionario.pPaginaPrecId) &&
        Objects.equals(this.pPaginaSuccId, paginaQuestionario.pPaginaSuccId) &&
        Objects.equals(this.pQuestionarioDes, paginaQuestionario.pQuestionarioDes) &&
        Objects.equals(this.pQuestionarioNote, paginaQuestionario.pQuestionarioNote) &&
        Objects.equals(this.questionarioId, paginaQuestionario.questionarioId) &&
        Objects.equals(this.des, paginaQuestionario.des) &&
        Objects.equals(this.numeroRisposte, paginaQuestionario.numeroRisposte) &&
        Objects.equals(this.paragrafi, paginaQuestionario.paragrafi) &&
        Objects.equals(this.tagsWeb, paginaQuestionario.tagsWeb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paginaId, elemCod, elementiDes, elementiNota, note, questCompId, userCompId, questionarioCod, pPaginaPrecId, pPaginaSuccId, pQuestionarioDes, pQuestionarioNote, questionarioId, des, numeroRisposte, paragrafi, tagsWeb);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginaQuestionario {\n");
    
    sb.append("    paginaId: ").append(toIndentedString(paginaId)).append("\n");
    sb.append("    elemCod: ").append(toIndentedString(elemCod)).append("\n");
    sb.append("    elementiDes: ").append(toIndentedString(elementiDes)).append("\n");
    sb.append("    elementiNota: ").append(toIndentedString(elementiNota)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    questCompId: ").append(toIndentedString(questCompId)).append("\n");
    sb.append("    userCompId: ").append(toIndentedString(userCompId)).append("\n");
    sb.append("    questionarioCod: ").append(toIndentedString(questionarioCod)).append("\n");
    sb.append("    pPaginaPrecId: ").append(toIndentedString(pPaginaPrecId)).append("\n");
    sb.append("    pPaginaSuccId: ").append(toIndentedString(pPaginaSuccId)).append("\n");
    sb.append("    pQuestionarioDes: ").append(toIndentedString(pQuestionarioDes)).append("\n");
    sb.append("    pQuestionarioNote: ").append(toIndentedString(pQuestionarioNote)).append("\n");
    sb.append("    questionarioId: ").append(toIndentedString(questionarioId)).append("\n");
    sb.append("    des: ").append(toIndentedString(des)).append("\n");
    sb.append("    numeroRisposte: ").append(toIndentedString(numeroRisposte)).append("\n");
    sb.append("    paragrafi: ").append(toIndentedString(paragrafi)).append("\n");
    sb.append("    tagsWeb: ").append(toIndentedString(tagsWeb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

