/*
 * ESSE3 Questionari API
 * API REST di ESSE3 per l'accesso ai questionari
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.epic_guys.esse4.models.questionari;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

/**
 * TagsWeb
 */
public class TagsWeb {
  @SerializedName("paginaId")
  private Integer paginaId = null;

  @SerializedName("tagCod")
  private String tagCod = null;

  @SerializedName("tagValAlfa")
  private String tagValAlfa = null;

  @SerializedName("tagValId")
  private String tagValId = null;

  @SerializedName("tagValNum")
  private Float tagValNum = null;

  @SerializedName("tagValData")
  private String tagValData = null;

  @SerializedName("visFlg")
  private Integer visFlg = null;

  public TagsWeb paginaId(Integer paginaId) {
    this.paginaId = paginaId;
    return this;
  }

   /**
   * Get paginaId
   * @return paginaId
  **/

  public Integer getPaginaId() {
    return paginaId;
  }

  public void setPaginaId(Integer paginaId) {
    this.paginaId = paginaId;
  }

  public TagsWeb tagCod(String tagCod) {
    this.tagCod = tagCod;
    return this;
  }

   /**
   * Get tagCod
   * @return tagCod
  **/

  public String getTagCod() {
    return tagCod;
  }

  public void setTagCod(String tagCod) {
    this.tagCod = tagCod;
  }

  public TagsWeb tagValAlfa(String tagValAlfa) {
    this.tagValAlfa = tagValAlfa;
    return this;
  }

   /**
   * Get tagValAlfa
   * @return tagValAlfa
  **/

  public String getTagValAlfa() {
    return tagValAlfa;
  }

  public void setTagValAlfa(String tagValAlfa) {
    this.tagValAlfa = tagValAlfa;
  }

  public TagsWeb tagValId(String tagValId) {
    this.tagValId = tagValId;
    return this;
  }

   /**
   * Get tagValId
   * @return tagValId
  **/

  public String getTagValId() {
    return tagValId;
  }

  public void setTagValId(String tagValId) {
    this.tagValId = tagValId;
  }

  public TagsWeb tagValNum(Float tagValNum) {
    this.tagValNum = tagValNum;
    return this;
  }

   /**
   * Get tagValNum
   * @return tagValNum
  **/

  public Float getTagValNum() {
    return tagValNum;
  }

  public void setTagValNum(Float tagValNum) {
    this.tagValNum = tagValNum;
  }

  public TagsWeb tagValData(String tagValData) {
    this.tagValData = tagValData;
    return this;
  }

   /**
   * Get tagValData
   * @return tagValData
  **/

  public String getTagValData() {
    return tagValData;
  }

  public void setTagValData(String tagValData) {
    this.tagValData = tagValData;
  }

  public TagsWeb visFlg(Integer visFlg) {
    this.visFlg = visFlg;
    return this;
  }

   /**
   * Get visFlg
   * @return visFlg
  **/

  public Integer getVisFlg() {
    return visFlg;
  }

  public void setVisFlg(Integer visFlg) {
    this.visFlg = visFlg;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagsWeb tagsWeb = (TagsWeb) o;
    return Objects.equals(this.paginaId, tagsWeb.paginaId) &&
        Objects.equals(this.tagCod, tagsWeb.tagCod) &&
        Objects.equals(this.tagValAlfa, tagsWeb.tagValAlfa) &&
        Objects.equals(this.tagValId, tagsWeb.tagValId) &&
        Objects.equals(this.tagValNum, tagsWeb.tagValNum) &&
        Objects.equals(this.tagValData, tagsWeb.tagValData) &&
        Objects.equals(this.visFlg, tagsWeb.visFlg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paginaId, tagCod, tagValAlfa, tagValId, tagValNum, tagValData, visFlg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagsWeb {\n");
    
    sb.append("    paginaId: ").append(toIndentedString(paginaId)).append("\n");
    sb.append("    tagCod: ").append(toIndentedString(tagCod)).append("\n");
    sb.append("    tagValAlfa: ").append(toIndentedString(tagValAlfa)).append("\n");
    sb.append("    tagValId: ").append(toIndentedString(tagValId)).append("\n");
    sb.append("    tagValNum: ").append(toIndentedString(tagValNum)).append("\n");
    sb.append("    tagValData: ").append(toIndentedString(tagValData)).append("\n");
    sb.append("    visFlg: ").append(toIndentedString(visFlg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

